### ISSUE TITLE
Consumir API para cadastrar usuário - Erros

### ISSUE THREAD

**Issue by pedroHenriqueAmaral** [TaskManager-SIS/task-manager-sistema-web#1]
- [x] No formulário de *cadastrar usuário*, precisa **exibir um texto em vermelho embaixo** do mesmo, referente a necessidade de preenchimento.
- [x] A mensagem de erro está atualmente em cor verde, **alterar para vermelha**, além das informações digitadas **serem limpadas caso ocorra o erro.**
- [x] Campo de senha e confirmar senha preenchidos, não é alertado se os demais não estão preenchidos e pedindo para que o façam.
- [x] E-mail inválido está exibindo a mensagem incorreta.

**Comment by Gabriel11022001** [comment]
- O usuário não preencheu o campo de nome, apresentar a mensagem "Informe seu nome" abaixo do campo com cor vermelha
- O usuário não preencher o campo de e-mail, apresentar a mensagem "Informe seu e-mail" abaixo do campo com cor vermelha
- O usuário não preencher o campo de senha, apresentar a mensagem "Informe sua senha" abaixo do campo com cor vermelha
- O usuário não preencher o campo de confirmação senha, apresentar a mensagem "Digite novamente sua senha" abaixo do campo com cor vermelha

**Comment by Gabriel11022001** [comment]
Erro: quando ocorre um erro o alerta de erro está com a cor verde e ele deve estar com a cor vermelha

**Comment by Gabriel11022001** [comment]
Erro:

**Comment by Gabriel11022001** [comment]
Erro: quando a senha e a senha de confirmação são preenchidas de forma divergente e os outros campos não são preenchidos, não é alertado que os outros campos, no caso nome e e-mail, devem ser preenchidos.

**Comment by Gabriel11022001** [comment]
Erro: quando ocorre algum erro, os campos do formulário são apagados.

**Comment by Gabriel11022001** [comment]
Erro: Quando o usuário informa um e-mail inválido, é apresentado um alerta com a mensagem incorreta, a mensagem que deve ser apresentada é a mensagem "E-mail inválido, informe um e-mail válido para concluir o cadastro!"

**Comment by lucassantana1** [comment]
Erros do sistema web corrigidos
